#!/usr/bin/env bash

if [ "$0" = "$BASH_SOURCE" ];then
	echo "You should source this script to benefit of aliases"
	exit 0
fi

n_nodes=2
if [ "$#" == "1" ];then
	n_nodes=$1
fi

start_regtest () {
	PREFIX_DIR="$PWD/regtest"
	if ! test -d "$PREFIX_DIR";then
		mkdir "$PREFIX_DIR"
	fi

	for i in `seq $n_nodes`;do
		bc_rpc=$((9000 + $i))
		bc_port=$((10000 + $i))
		bc_dir="$PREFIX_DIR/bcdir$i"
		ln_port=$((11000 + $i))
		ln_dir="$PREFIX_DIR/lndir$i"
		mkdir "$bc_dir"
		bitcoind -daemon -regtest -rpcpassword="test" -rpcuser="test" -rpcport="$bc_rpc" -datadir="$bc_dir" -bind="127.0.0.1:$bc_port" > /dev/null
		echo "Started bitcoind n.$i with P2P port $bc_port, RPC port $bc_rpc and datadir $bc_dir"
		sleep 0.2
		lightningd --daemon --network regtest --bitcoin-rpcuser test --bitcoin-rpcpassword test --bitcoin-datadir "$bc_dir" --bitcoin-rpcport $bc_rpc --bind-addr "127.0.0.1:$ln_port" --lightning-dir "$ln_dir" --alias "testnode$i" > /dev/null
		echo "Started lightningd on top of it with directory $ln_dir"
		echo ""
		alias "bcreg$i"="bitcoin-cli -regtest -rpcpassword=test -rpcuser=test -rpcport=$bc_rpc"
		alias "lnreg$i"="lightning-cli --lightning-dir $ln_dir"
	done

	echo ""
	echo "Started $n_nodes pairs of bitcoind and lightningd nodes with rpc user \"test\" and pass \"test\"."
	echo "You can access them using aliases created for each one : bcregi and lnregi with i the node number for bitcoin-cli and lightning cli."
	echo "For example you can try with \"bcreg2 getblockchaininfo\" and \"lnreg2 getinfo\" "
}

stop_regtest () {
	PREFIX_DIR="$PWD/regtest"
	if ! test -d "$PREFIX_DIR";then
		mkdir "$PREFIX_DIR"
	fi

	echo "lightningd can take some time to stop. It will be fixed in v0.7.2"
	for i in `seq $n_nodes`;do
		lightning-cli --lightning-dir "$PREFIX_DIR/lndir$i" stop > /dev/null
		rm -rf "$PREFIX_DIR/lndir$i"
		echo "lightningd n.$i stopped"
		sleep 0.1
		bitcoin-cli -regtest -rpcpassword=test -rpcuser=test -rpcport=$((9000 + $i)) stop > /dev/null
		rm -rf "$PREFIX_DIR/bcdir$i"
		echo "bitcoind n.$i stopped"
	done
}
