#!/usr/bin/env bash

if [ "$0" = "$BASH_SOURCE" ];then
	echo "You should source this script to benefit of aliases"
	exit 0
fi

n_nodes=2
if [ "$#" == "1" ];then
	n_nodes=$1
fi

for i in `seq $n_nodes`;do
	bc_rpc=$((9000 + $i))
	bc_port=$((10000 + $i))
	bc_dir="$PWD/bcdir$i"
	ln_port=$((11000 + $i))
	mkdir "$bc_dir"
	bitcoind -daemon -regtest -rpcpassword="test" -rpcuser="test" -rpcport="$bc_rpc" -datadir="$bc_dir" -bind="127.0.0.1:$bc_port"
	echo "Started bitcoind n.$i with P2P port $bc_port, RPC port $bc_rpc and datadir $bc_dir"
	sleep 0.5
	echo "lightningd --network regtest --bitcoin-rpcuser test --bitcoin-rpcpassword test --bitcoin-datadir \"$bc_dir\" --bitcoin-rpcport $bc_rpc --bind-addr \"127.0.0.1:$ln_port\" --lightning-dir \"lndir$i\" --alias \"testnode$i\""
	lightningd --daemon --network regtest --bitcoin-rpcuser test --bitcoin-rpcpassword test --bitcoin-datadir "$bc_dir" --bitcoin-rpcport $bc_rpc --bind-addr "127.0.0.1:$ln_port" --lightning-dir "lndir$i" --alias "testnode$i"
	echo "Started lightningd on top of it with directory lndir$i"
	alias bcreg$i="bitcoin-cli -regtest -rpcpassword=test -rpcuser=test -rpcport=$bc_rpc"
	alias lnreg$i="lightning-cli --lightning-dir lndir$i"
done

echo "Started $n_nodes bitcoind and lightningd nodes with rpc user \"test\" and pass \"test\"."
echo "You can access them using aliases created for each one : bcregI and lnregI with i the node number for bitcoin-cli and lightning cli."
echo "For example you can try with \"bcreg2 getblockchaininfo\" and \"lnreg2 getinfo\" "
